spring.application.name=SpringDataJPA
spring.datasource.url= jdbc:mysql://localhost:3306/attendance
spring.datasource.username= root
spring.datasource.password= pav$wap_is@l1ve4devinc$&fun

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=mysql