spring.application.name=CLIDBAccessTool
spring.datasource.url=jdbc:mysql://localhost:3306/record
spring.datasource.username=root
spring.datasource.password=pav$wap_is@l1ve4devinc$&fun

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Optional but useful
spring.jpa.show-sql=true