spring.application.name=SpringDataJPA
spring.datasource.url= jdbc_link
spring.datasource.username= your_username
spring.datasource.password= Your_password

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=mysql