spring.application.name=CLIDBAccessTool
spring.datasource.url= jdbc url of your database connection
spring.datasource.username= your username
spring.datasource.password= your password

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

